services:
  trafik:
    image: docker.io/traefik:v3.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./src/docker/local/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - banking_local_network
    command:
      - --providers.docker=true
  api: &api
    build:
      context: .
      dockerfile: ./src/docker/local/fastapi/Dockerfile
    volumes:
      - .:/src
      - ./backend/app/logs:/src/logs
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
    command: /start.sh
    networks:
      - banking_local_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.service=api-service"
      - "traefik.http.services.api-service.loadbalancer.server.port=8000"
  mailpit:
    image: docker.io/axllent/mailpit:v1.20.3
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - banking_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_ALLOW_INSECURE_AUTH: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SMTP_ALLOW_INSECURE: 1
      MP_TLS_SKIP_VERIFY: 1
      MP_SSL_SKIP_VERIFY: 1
      MP_LOG_LEVEL: debug
    networks:
      - banking_local_network
  postgres:
    build:
      context: .
      dockerfile: ./src/docker/local/postgres/Dockerfile
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - banking_local_network
networks:
  banking_local_network:
    external: true
    driver: bridge
volumes:
  postgres_data:
  banking_mailpit_data: